spring:
  application:
    name: eureka-client-demo
#  cloud:
#    consul:
#      host: localhost
#      port: 9600

server:
  port: 9702
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9700/eureka/
